[project]
name = "IDAPython"
version = "0.1.0"
description = "FFXIVClientStructs IDA scripts"
authors = [
    { name = "aers" },
    { name = "daemitus" },
    { name = "pohky" },
    { name = "nonowazu" },
]
requires-python = ">=3.10,<4"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
[project.dependencies]
PyYAML = ">=6.0,<7"

[project.optional-dependencies]
idarename = [
    "anytree>=2.8.0,<3",
]
sigmaker = [
    "dacite>=1.6.0,<2",
]
all = ["anytree>=2.8.0,<3", "dacite>=1.6.0,<3"]

[dependency-groups]
dev = []

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
