[project]
name = "IDAPython"
version = "0.1.0"
description = "FFXIVClientStructs IDA scripts"
authors = [
    { name = "aers" },
    { name = "daemitus" },
    { name = "pohky" },
    { name = "nonowazu" },
]
requires-python = ">=3.10,<4"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = ["PyYAML>=6.0.1,<7"]

[project.optional-dependencies]
idarename = [
    "anytree>=2.8.0,<3",
]
sigmaker = [
    "dacite>=1.6.0,<2",
]
all = ["anytree>=2.8.0,<3", "dacite>=1.6.0,<2"]

[dependency-groups]
dev = [
    "ruff>=0.15.8",
]

[tool.ruff]
target-version = "py310"
line-length = 120


[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = ["E741", "B006"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
